# Generated by Django 2.2.5 on 2019-09-10 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensajero', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensaje',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
