# Generated by Django 2.2.5 on 2019-09-10 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensajero', '0002_auto_20190910_1511'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hilo',
            options={'ordering': ['-fecha_actualizar']},
        ),
        migrations.AddField(
            model_name='hilo',
            name='fecha_actualizar',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
